version: '3'

services:
    client:
      build: ./client
      ports:
        - 3000:3000
      environment:
        - TIME_TRACKER_API_BASE_URL=server
      depends_on:
        - server
    
    server:
      build: ./server
      ports:
        - 9000:9000
      environment:
        - PORT=9000
        - APP_NAME=time-tracker-api
        - ENCRYPTION_KEY=uMlZlHeAEU3w3X+sDQLT9Q==
        - POSTGRES_HOST=postgres
        - POSTGRES_PORT=5432
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=time-tracker
        - PGADMIN_DEFAULT_EMAIL=admin@admin.com
        - PGADMIN_DEFAULT_PASSWORD=Draco123
        - DEFAULT_ADMIN_EMPLOYEE_EMAIL=contact@lulosoft.com
        - DEFAULT_ADMIN_EMPLOYEE_PASSWORD=myLu!o5of^!
        - INVOICE_EMAIL_SENDER_ADDRESS=juan.espinosa@lulosoft.com
        - INVOICE_EMAIL_SENDER_PASSWORD=Draco123
      depends_on:
        - postgres
      command: sh -c 'dockerize -wait tcp://postgres:5432 -- node ./build/bin/www.js'

    postgres:
        image: postgres:11.5
        ports:
            - "5432:5432"
        volumes:
            - /Users/data/postgres:/data/postgres
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=time-tracker
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=admin